### ISSUE TITLE
Change to New Azure Icon

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/vscode-node-azure-pack#19]
The Azure Icon recently changed to one that matches fluid design

https://azure.microsoft.com/en-us/blog/a-fluent-new-look-for-the-azure-icon/

**Comment by isaacrlevin** [comment]
![azure-new](https://user-images.githubusercontent.com/8878502/118296150-7c15e780-b491-11eb-833e-a63f4ca7a6d0.png)

**Comment by gregvanl** [comment]
Hi @isaacrlevin This looks like it was done https://github.com/microsoft/vscode-node-azure-pack/blob/main/azure.png
Is there anything else that you see needs to be updated?

**Comment by isaacrlevin** [comment]
Nope, that is it! Thanks!
