### ISSUE TITLE
Add Azure DevOps Pull Request support

### ISSUE THREAD

**Issue by sa-schiefer** [microsoft/vscode-node-azure-pack#21]
While there has been PR support for GitHub for about 3 years, there is still no proper PR support for Azure DevOps.

Azure Repos being an integral part of Azure DevOps support for PR needs to be added. 

I understand that GitHub has a vastly bigger user base but having increasingly more features ignoring Azure for GitHub creates a very inconsistent and unpleasant experience.

**Comment by bwateratmsft** [comment]
This seems like a request for Azure DevOps; this repo is for the Azure Tools VSCode extension pack.
