### ISSUE TITLE
The deployment process gets stuck in "Analyzing your repository" 

### ISSUE THREAD

**Issue by zamsame** [microsoft/vscode-node-azure-pack#32]
![repo](https://user-images.githubusercontent.com/99767009/166318616-ca8b17d9-6e4b-4623-ad25-50f3c4bc7bb7.PNG)
![repoerror](https://user-images.githubusercontent.com/99767009/166318620-c9fb9a2b-e7eb-4aab-841e-4c97379d0b3d.PNG)

During the process: "Analyzing your repository" its gets stuck and doesn't move forward to the next steps of deployment. 
we don't get an error message, the process just doesn't finish.
Any advice to solve the issue?

**Comment by bwateratmsft** [comment]
The [extension](https://github.com/microsoft/vscode-deploy-azure) has been deprecated, so I will close this issue.
