### ISSUE TITLE
Open bash/powershell in Cloud shell options missing in MacOS Azure Tools Plugin 

### ISSUE THREAD

**Issue by p2a8t4a5a** [microsoft/vscode-node-azure-pack#41]
Installed Azure Tools/ Azure Account extension on VSCode MacOS
Azure: Open Bash in Cloud Shell
Azure: Open PowerShell in Cloud Shell 
missing

**Comment by nturinski** [comment]
The `Azure: Open Bash in Cloud Shell` and `Azure: Open PowerShell in Cloud Shell` commands have been replaced with entry points in the VS Code terminal view. See [README.md](https://github.com/microsoft/vscode-azure-account#azure-cloud-shell) for more details.
