### ISSUE TITLE
Selecting default AzureML workspace doesn't ask for resource group

### ISSUE THREAD

**Issue by fschlz** [microsoft/vscode-node-azure-pack#55]
I've got some AzureML workspaces, that have the same name.
So, I cannot select any of them, b/c I cannot see which ones which.
(The sidebar shows it, once I selected one, but then I'd have to iterate all of them to find the correct one. And that doesn't guarantee that the sorting in the workspace selector doesn't change.)

Flow rn is:
1. click bottom bar "Azure ML Workspace: xxx"
2. in top center selector pops up where you choose the subscription
3. then you immediately choose the AzureML workspace 👈 broken b/c of above reason

instead, the flow should look like this:
1. click bottom bar "Azure ML Workspace: xxx"
2. in top center selector pops up where you choose the subscription
3. then select resource group (from this the plugin should be able to figure out itself which Azure Workspace it is)

**Comment by bwateratmsft** [comment]
Hey @fschlz, it looks like you want to file this issue [here](https://github.com/microsoft/vscode-tools-for-ai/issues) instead
