### ISSUE TITLE
Unable to Sign Out

### ISSUE THREAD

**Issue by erikpa1** [microsoft/vscode-node-azure-pack#64]
Hi, when I don't see some subscriptions I just Sign Out and Sign In, but it's not possible to Sign Out... even I can't uninstall the plugin, it's always there. It's impossible to kill it even when I REINSTAL VS Code

![image](https://github.com/microsoft/vscode-node-azure-pack/assets/19526670/0da5f830-d8d8-440b-ab89-4386b80882b8)

**Comment by alexweininger** [comment]
The Azure view is contributed by the Azure Resources extension, uninstalling that will remove the view. https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureresourcegroups
